In [22]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [23]:
 df = pd.read_csv("interview_assessment.csv")


In [24]:
df

experience  test_score  interview_score  salary($)
0        NaN         8.0                9      50000
1        NaN         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

In [25]:
!pip install word2number # for converting word into numbers

You should consider upgrading via the 'c:\users\omen\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [26]:
 from word2number import w2n
w2n.word_to_num("three")

3

In [34]:
df['experience'] = df.experience.fillna("zero") # first we filled the blank with zero 

In [35]:
df

experience  test_score  interview_score  salary($)
0       zero         8.0                9      50000
1       zero         8.0                6      45000
2       five         6.0                7      60000
3        two        10.0               10      65000
4      seven         9.0                6      70000
5      three         7.0               10      62000
6        ten         NaN                7      72000
7     eleven         7.0                8      80000

In [37]:
df['experience'] = df.experience.apply(w2n.word_to_num) # then we apply the function

In [38]:
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         NaN                7      72000
7          11         7.0                8      80000

In [39]:
#missing value in test case

In [43]:
 medi = df.test_score.median()

In [46]:
df.test_score = df.test_score.fillna(medi)

In [47]:
df

experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         8.0                7      72000
7          11         7.0                8      80000

In [48]:
reg = linear_model.LinearRegression()


In [51]:
reg.fit(df[['experience','test_score','interview_score']],df['salary($)'])

LinearRegression()

In [55]:
reg.predict([[12,9,6]])

array([81335.51673945])

In [61]:
reg.predict([[7,9,6]])

array([67270.74235808])

In [58]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [59]:
reg.intercept_

17737.263464337666